"""
add user and refresh token tables.

Revision ID: 57fac5921361
Create Date: 2026-10-09 16:30:18.724591

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "57fac5921361"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Migrate forward."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("datetime_created", sa.DateTime(timezone=True), nullable=False),
        sa.Column("datetime_updated", sa.DateTime(timezone=True), nullable=False),
        sa.Column("datetime_disabled", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "email", sqlmodel.sql.sqltypes.AutoString(length=320), nullable=False
        ),
        sa.Column(
            "first_name", sqlmodel.sql.sqltypes.AutoString(length=150), nullable=False
        ),
        sa.Column(
            "last_name", sqlmodel.sql.sqltypes.AutoString(length=150), nullable=False
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "password_hash", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True
        ),
        sa.Column(
            "groups",
            postgresql.ARRAY(sa.String(length=32)),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user")),
        sa.UniqueConstraint("email", name=op.f("uq_user_email")),
    )
    op.create_table(
        "refreshtoken",
        sa.Column("datetime_created", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("family_id", sa.Uuid(), nullable=False),
        sa.Column(
            "token_hash", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False
        ),
        sa.Column("datetime_expires", sa.DateTime(timezone=True), nullable=False),
        sa.Column("datetime_revoked", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
            name=op.f("fk_refreshtoken_user_id_user"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_refreshtoken")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_refreshtoken_token_hash")),
    )
    op.create_index(
        op.f("ix_refreshtoken_family_id"), "refreshtoken", ["family_id"], unique=False
    )
    op.create_index(
        op.f("ix_refreshtoken_user_id"), "refreshtoken", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Migrate backwards."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_refreshtoken_user_id"), table_name="refreshtoken")
    op.drop_index(op.f("ix_refreshtoken_family_id"), table_name="refreshtoken")
    op.drop_table("refreshtoken")
    op.drop_table("user")
    # ### end Alembic commands ###
